apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
  name: shoot-oidc-service
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: garden.local.gardener.cloud:5001/gardener-project/public/charts/gardener/extensions/shoot-oidc-service:v0.35.0-dev
  resources:
  - clusterCompatibility:
    - garden
    - shoot
    kind: Extension
    type: shoot-oidc-service
    workerlessSupported: true
